version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - app
networks:
  app-network:
    driver: bridge
